### ISSUE TITLE
Fix export with IFS

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#117]
## Example

```bash
minishell$ export A="a b c"
minishell$ echo $A
a
```

```bash
minishell$ export A="a a" # OK
minishell$ export A="a 1" # NG
minishell: export: `1': not a valid identifier
minishell$ export A="1 2 3 4" #NG
minishell: export: `2': not a valid identifier
minishell: export: `3': not a valid identifier
minishell: export: `4': not a valid identifier
```

**Comment by alex216** [comment]
same with cd
```bash
$ cd 'hello world'
$(move to hello\ world directory)

minishell$ cd 'hello world'
minishell: cd: too many arguements
```

**Comment by alex216** [comment]
> ## Example
> ```shell
> minishell$ export A="a b c"
> minishell$ echo $A
> a
> ```
> 
> ```shell
> minishell$ export A="a a" # OK
> minishell$ export A="a 1" # NG
> minishell: export: `1': not a valid identifier
> minishell$ export A="1 2 3 4" #NG
> minishell: export: `2': not a valid identifier
> minishell: export: `3': not a valid identifier
> minishell: export: `4': not a valid identifier
> ```

`export A="a a"` is not OK either.
```shell
bash$ export A="a a"
bash$ echo $A
a a
```
