### ISSUE TITLE
is_valid_head_token_simple_command()

### ISSUE THREAD

**Issue by alex216** [rask24/minishell#79]
suggestion:
`is_valid_head_of_simple_command_token()`?
`is_valid_head_token_of_simple_command()`?
`is_valid_head_of_simple_command()`?

**Comment by rask24** [comment]
https://softwareengineering.stackexchange.com/questions/404135/use-prepositions-in-naming-verb-phrase-functions

**Comment by rask24** [comment]
https://github.com/rask24/minishell/blob/main/src/parser/try_parse_redirect.c#L25

**Comment by rask24** [comment]
Resolved in #165.
We've decided to adopt the name `is_simple_command_first_set` for this function.
